version: '3.8'

services:
  fastapi:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - minio

  worker:
    build: ./backend
    command: celery -A app.core.celery_app worker -l info
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - redis
      - fastapi

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=plum
      - POSTGRES_PASSWORD=plum123
      - POSTGRES_DB=claims
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi

  prometheus:
    image: prom/prometheus:v2.37.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - fastapi

  grafana:
    image: grafana/grafana:8.5.2
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres_data:
  minio_data:
